'use strict';

const HandleShowChannelModelCommandAsync = require('../src/chat-commands/show-channel-model-command');
const { ModelIdentityPattern } = require('../src/chat-commands/show-channel-model-command');

// ── Helpers ───────────────────────────────────────────────────────────────────

function MakeEnv() {
  const SlackApp = {
    Logger: { info: jest.fn(), warn: jest.fn(), error: jest.fn() },
    PostMessageTextAsync: jest.fn().mockResolvedValue(undefined),
  };

  const EventInfo = { channel: 'C_GENERAL', ts: '1700000000.000001', user: 'U_ASKER', text: '' };

  const BuildChannelModelStatus = jest.fn().mockReturnValue({
    override: null,
    defaultModel: 'gpt-4o-mini',
    effectiveModel: 'gpt-4o-mini',
    lines: [
      'Channel override: _(none — using workspace default)_',
      'Channel basic model: `gpt-4o-mini`',
      'Workspace default chat model: `gpt-4o-mini`',
    ],
  });

  return { SlackApp, EventInfo, BuildChannelModelStatus };
}

// ── Model-identity routing pattern ────────────────────────────────────────────

describe('model-identity routing pattern', () => {
  test.each([
    'what model are you running on this channel?',
    'which model are you running right now',
    'What model are you using?',
    'what model are you',
    'what model are you?',
    'which model are you on right now?',
    'what AI model are you running',
    'what chat model are you using',
    'which model is this channel using',
    'what model is the channel running',
    'what model is running in this channel',
    'what model is active right now',
    'what model are you using right now?',
  ])('matches "%s"', (Input) => {
    expect(ModelIdentityPattern.test(Input)).toBe(true);
  });

  test.each([
    'what models are available right now',          // plural → live-model-catalog-question route
    'which chatgpt models can this workspace use',  // plural availability question
    'switch models',                                // model-switch family
    'what model should I use',                      // advice question, not identity
    'show-channel-model',                           // literal command has its own strict route
    'set-channel-model',                            // different command
    'tell me what model are you running',           // not anchored at message start
    'what model are you running on that channel',   // only "this channel" is deterministic
    'are you gpt or claude',                        // no what/which lead-in — falls through to chat
  ])('does not match "%s"', (Input) => {
    expect(ModelIdentityPattern.test(Input)).toBe(false);
  });
});

// ── Handler output ────────────────────────────────────────────────────────────

describe('HandleShowChannelModelCommandAsync', () => {
  test('posts the channel status block with verified-answer framing', async () => {
    const Env = MakeEnv();

    await HandleShowChannelModelCommandAsync(Env.SlackApp, Env.EventInfo, Env.BuildChannelModelStatus);

    expect(Env.BuildChannelModelStatus).toHaveBeenCalledWith('C_GENERAL');
    expect(Env.SlackApp.PostMessageTextAsync).toHaveBeenCalledTimes(1);

    const [Channel, ThreadTS, Text] = Env.SlackApp.PostMessageTextAsync.mock.calls[0];
    expect(Channel).toBe('C_GENERAL');
    expect(ThreadTS).toBe('1700000000.000001');
    expect(Text).toContain('*Channel Model* — <#C_GENERAL>');
    expect(Text).toContain('Channel basic model: `gpt-4o-mini`');
    expect(Text).toContain('Workspace default chat model: `gpt-4o-mini`');
    expect(Text).toContain(':white_check_mark: _Verified answer');
    expect(Text).toContain('not generated by the AI model');
  });

  test('reports an override when one is set', async () => {
    const Env = MakeEnv();
    Env.BuildChannelModelStatus.mockReturnValue({
      override: 'claude-fable-5',
      defaultModel: 'gpt-4o-mini',
      effectiveModel: 'claude-fable-5',
      lines: [
        'Channel override: `claude-fable-5`',
        'Channel basic model: `claude-fable-5`',
        'Workspace default chat model: `gpt-4o-mini`',
      ],
    });

    await HandleShowChannelModelCommandAsync(Env.SlackApp, Env.EventInfo, Env.BuildChannelModelStatus);

    const Text = Env.SlackApp.PostMessageTextAsync.mock.calls[0][2];
    expect(Text).toContain('Channel override: `claude-fable-5`');
    expect(Text).toContain('Channel basic model: `claude-fable-5`');
  });
});
